### PR TITLE
#84 fix comment button <item>

### LINKED ISSUE #84: Fix css and button functionality on matching/missing bikes <item>

### PR DESCRIPTION
**Pull request by FredSoderberg**
#### What does this PR do?
Basically it fixes the linking for the comment button in profile (and browser). A refactoring of how we handle bikeInformation/item/comments is probably needed but in my opinion not vital right now.
[#84](LINK_TO_ISSUE)

##### Why are we doing this? Any context or related work?
There was numerous linking bugs previously. Its still somewhat of a mess but it "should" work better now. Mainly the use of linked props and not using states.

#### Where should a reviewer start?
profile.renderItem -> BikeInformation -> Item

#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #84

### CODE REVIEW

File: Bikeini/components/Item.js [hunk 1]
```diff
@@ -71,8 +75,24 @@ export default class Item extends React.PureComponent {
...
+              bikeData.showComments = true;
+              navigation.navigate('BikeInformation', { data: bikeData });
+            }}
+          >
+            <Image style={styles.commentsTag} source={commentIcon} />
+
+          </TouchableOpacity>
+          <TouchableOpacity
+            style={styles.locationTag}
+            onPress={() => { Alert.alert('Position me biatch'); }}
```
Comment (erikajansson1) [inline Bikeini/components/Item.js]: Remove biatch, not the greatest word here...

**Comment by erikajansson1** [comment]
Well done, change what is requested in comment above then it is fine!

File: Bikeini/components/Item.js (hunk 1 above)
Comment (FredSoderberg) [reply Bikeini/components/Item.js]: pc-fever

**Review by erikajansson1 — APPROVED** [review]
