### PR TITLE
#100 css fix

### LINKED ISSUE #100: Beautify the application with css magic

### PR DESCRIPTION
**Pull request by erikajansson1**
#### What does this PR do?
Fix css for profile, add, game and browser screen
[Issue](#100 )

##### Why are we doing this? Any context or related work?
To give the user a better experience
#### Where should a reviewer start?
Any of the above mentioned screens. 
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #100

### CODE REVIEW

File: Bikeini/screens/Gamification.js [hunk 1]
```diff
@@ -2,63 +2,85 @@ import React from 'react';
...
 import { connect } from 'react-redux';
 import {
-  StyleSheet, Text, View, ScrollView, Image, FlatList,
+  StyleSheet, Text, View, ScrollView, Image, FlatList, ImageBackground,
 } from 'react-native';
 import headerStyle from './header';
 import serverApi from '../utilities/serverApi';
 
 const profilePic = require('../assets/images/userPlaceholder.jpg');
+const background = require('../assets/images/background.jpeg');
```
Comment (FredSoderberg) [inline Bikeini/screens/Gamification.js:11]: Beutiful

File: Bikeini/screens/Gamification.js [hunk 2]
```diff
@@ -2,63 +2,85 @@ import React from 'react';
...
+  },
+  backImg: {
+    flex: 1,
+    alignSelf: 'stretch',
+  },
+  listBack: {
+    backgroundColor: 'white',
+    width: '75%',
+    left: '12%',
+    borderRadius: 15,
```
Comment (FredSoderberg) [inline Bikeini/screens/Gamification.js:83]: Very very nice

**Review by FredSoderberg — APPROVED** [review]
There are still a lot to do and more to come. This will have to wait though so this is approved and a nice addition to our current style
