### PR TITLE
fixed endless loop

### LINKED ISSUE #77: State update is a endless loop in bike information

### PR DESCRIPTION
**Pull request by FredSoderberg**
#### What does this PR do?
Fix endless state updating loop in bike information
[#77](LINK_TO_ISSUE)

##### Why are we doing this? Any context or related work?
Hot fix for performance
#### Where should a reviewer start?
bikeinfomation
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
close #77

### CODE REVIEW

File: Bikeini/screens/BikeInformation.js [hunk 1]
```diff
@@ -322,6 +306,14 @@ class BikeInformation extends React.Component {
     // const { city, neighborhood } = location;    <- Ingen cykel har samma data-format .....
     const city = location;
     const neighborhood = location;
+    if (!dataLoaded) {
+      console.log('loading');
```
Comment (erikajansson1) [inline Bikeini/screens/BikeInformation.js:310]: Is this necessary for future troubleshooting or can it be removed? If possible I think it should be removed!
