### PR TITLE
Fixed location integration with server.

### LINKED ISSUE #46: Verify 'location' screen server calls works like it should
Basically refactor and verify that location page works like it should and redirects to browser with the correct information

### PR DESCRIPTION
**Pull request by erikajansson1**
#### What does this PR do?
Fixes server integration on location screen. Also some code refactoring. 
[Issue](#46 )
https://github.com/Cykelinspektionen/MjukvaruProjekt/issues/46
##### Why are we doing this? Any context or related work?
To achieve minimum viable product.
#### Where should a reviewer start?
Location.js
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #46

### CODE REVIEW

File: Bikeini/screens/Location.js [hunk 1]
```diff
@@ -54,38 +54,38 @@ const styles = StyleSheet.create({
   },
 });
 
-let checkedCity = '';
```
Comment (FredSoderberg) [inline Bikeini/screens/Location.js:57]: NIce :D

File: Bikeini/screens/Location.js [hunk 2]
```diff
@@ -54,38 +54,38 @@ const styles = StyleSheet.create({
...
-    checkedCity = item;
-  } else if (checkedCity === item) {
-    this.setState({ checked: checked.filter(a => a !== item) });
-    checkedCity = '';
-  } else {
-    this.setState({ checked: checked.filter(a => a !== item) });
+  if (checked !== item) {
+    this.setState({ checked: item });
+  } else if (checked === item) {
+    this.setState({ checked: '' });
```
Comment (FredSoderberg) [inline Bikeini/screens/Location.js:70]: So nice nice refactor!

File: Bikeini/screens/Location.js [hunk 3]
```diff
@@ -54,38 +54,38 @@ const styles = StyleSheet.create({
...
+  }
+  const { authState, setLocation } = this.props;
+  const body = JSON.stringify({ location: checked });
+  serverApi.fetchApi('users/updateuser/', body, 'application/json', authState.jwt[0]);
+  setLocation(checked);
 }
 
 render() {
   const { checked } = this.state;
+  console.log('Check: ', checked);
```
Comment (FredSoderberg) [inline Bikeini/screens/Location.js:88]: remove in the future

**Comment by FredSoderberg** [comment]
Good work, nothing to fix
